### ISSUE TITLE
anzu-mode makes emacs unusable when searching in big files

### ISSUE THREAD

**Issue by gonewest818** [emacsorphanage/anzu#113]
As mentioned in `r/emacs`:

https://www.reddit.com/r/emacs/comments/gjekq3/anzumode_makes_emacs_unusable_when_searching_in/

**Comment by syohex** [comment]
I suppose this issue can be fixed by setting `anzu-search-threshold`

**Comment by gonewest818** [comment]
Thanks. In your experience, when was it necessary to set that threshold?

**Comment by syohex** [comment]
I set `1000` it in init.el. Because I often open large files. I suppose it is better to set non-nil value(e.g. 100, 1000) to it as default value rather than `nil`
